### ISSUE TITLE
SVG obrázek není vidět

### ISSUE THREAD

**Issue by uberales** [fykosak/dokuwiki-template-fkstpl#1]
SVG se mi vůbec neukazuje (http://195.113.23.5/fksweb/akce/fyziklani), vidím jen text fyziklani_stupinek.svg. Chrome 49.0.2623.87 m.

**Comment by cevro** [comment]
Sry, uprgadoval som wiki a prepísala conf/mine.conf.

Už je vidieť.

**Comment by LukasLedvina** [comment]
Na první load ve FF jsem replikoval uberales pripominku. Na druhy pokus uz to slo dobre.
FF(iceweasel)  38.7.1
