### ISSUE TITLE
Podbarvení sekcí

### ISSUE THREAD

**Issue by timkol** [fykosak/dokuwiki-template-fkstpl#10]
Podbarvit menu a další prvky (rámeček ankety) barvou dané sekce, kde se nacházím.

**Comment by cevro** [comment]
To pojde a veľa vecí je na to pripravených. :+1:

**Comment by cevro** [comment]
Viď test. Otázkou je čo všetko sa má zmeniť a prefarbiť.

**Comment by cevro** [comment]
Opravené, uzatváram.
