### ISSUE TITLE
Obsah sidebaru

### ISSUE THREAD

**Issue by timkol** [fykosak/dokuwiki-template-fkstpl#11]
Do sidebaru bych dal defaultně něco jiného, než anketu. Ale nevím co. Anketu bych dal jen na úvodní stránku.

**Comment by cevro** [comment]
defaultne je tam navigácia vrámci stránky, inak je tam sidebar, ak sa teda stránka sidebar_<lang> nachádza v danom namespace. Je to normálne dokuwiki stránka teda tam môže isť v princípe hocičo.

**Comment by cevro** [comment]
Asi je to zodpovedané, uzatváram.
