### ISSUE TITLE
Plocha na "úvodce" akce fádní

### ISSUE THREAD

**Issue by timkol** [fykosak/dokuwiki-template-fkstpl#12]
Barevná plocha na stránce akce je příliš fádní, na PC navíc možná příliš velká.

**Comment by cevro** [comment]
Môže sa tam dať fotka/farba/nemať nič, text farby ani to, kde budú tieto veľké uvodné "obrázky" sú len demonštracia toho čo to vie, isto to nieje definitívne a od tých čistých farieb môžme skludom upustiť.

**Comment by cevro** [comment]
Samotná farba sa už nikde nevyskytuje, teda to uzatváram.
