### ISSUE TITLE
Menu se pro některé šířky rozhodí na dvě řádky

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/dokuwiki-template-fkstpl#2]
Pro málo šířek (cca 20px) se menu rozpadne na dvě řádky:

![snimek z 2016-03-27 17 22 34](https://cloud.githubusercontent.com/assets/1250507/14066491/0c730fa4-f44b-11e5-87d0-781305bcf8e9.png)

**Comment by cevro** [comment]
opravené v 00f49361bb04b0b653592a282fa1d64f10d84852

**Comment by LukasLedvina** [comment]
Menu mám na dvou řádcích a zmizelo mi tlačítko vyhledat.
![Uploading Snímek z 2016-03-28 02:03:09.png…]()
