### ISSUE TITLE
Sponzoři loga - deformované - oddeformovat

### ISSUE THREAD

**Issue by syselkk** [fykosak/dokuwiki-template-fkstpl#29]
Když se podívám na web, tak vidím, že jsou loga deformovaná - minimálně jistě to matfyzu (už jsem zkoušel přikládat i měřítko - viz obrázek)

![loga](https://cloud.githubusercontent.com/assets/5481487/26286743/d4676426-3e6c-11e7-9622-b6da81e236c8.PNG)

**Comment by syselkk** [comment]
Ty čtverečky, co jsou na kraji, prostě mají být fakt čtverečky a ne obdélníčky.

**Comment by cevro** [comment]
spustil som FF a obecne sa mi zdá celá stránka deformovaná. Vyzerá že je problém s definíciou DPI v hlavičke.

**Comment by cevro** [comment]
Našiel som riešenie:
https://stackoverflow.com/questions/29551637/css-image-scaling-issue-with-flexbox-in-firefox-internet-explorer

Dnes v noci ho nasadím

**Comment by cevro** [comment]
Nasadene
