### ISSUE TITLE
Pomalý load

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/dokuwiki-template-fkstpl#3]
Nějaký FB nesmysl se natahuje asi 6s, pak teprve se začnou natahovat novinky a celkově to trvá k 10s.

GET /impression.php/f2d2cb80c006f7a/?api_key=911280978986775&lid=115&payload=%7B%22source%22%3A%22jssdk%22%7D HTTP/1.1
Host: www.facebook.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.7.1
Accept: image/png,image/_;q=0.8,_/*;q=0.5
Accept-Language: cs,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://195.113.23.5/fksweb/start
Cookie: datr=Mg5ZVXYfCe4qTLpzD-8zPzHl; fr=0DbAcvyDIaCH8blSe.AWXEsiLSrzTfXR0ktsgM3qL-OUg.BVWQ45.Zm.Fb2.0.AWVcyTML; lu=ThlCvqOSuMDk-7wsKtz_WprQ; c_user=1011662868; xs=39%3A-lb4Bx8J0Vt2PA%3A2%3A1432338097%3A9836; csm=2; s=Aa4jvq2U-NBgTJlK.BVX76x; p=-2; act=1459095551889%2F84; presence=EDvF3EtimeF1459096725EuserFA21011662868A2EstateFDsb2F1459060353533Et2F_5bDiFA2user_3a1B00502282697A2ErF1CAcDiFA2user_3a1B01730953798A2ErF1CAcDiFA2user_3a1B00373359067A2CAcDiFA2thread_3a992115564203256A2EsiFA2992115564203256A2C_5dElm2FA2user_3a1B01730953798A2Euct2F1459038865566EtrFnullEtwF458689916EatF1459095559711G459096725724CEchFDp_5f1011662868F442CC
Connection: keep-alive

**Comment by cevro** [comment]
https://github.com/fykosak/dokuwiki-plugin-fksnewsfeed/issues/4
