### ISSUE TITLE
EN logo má odkazovat na en stránku

### ISSUE THREAD

**Issue by sstenchlak** [fykosak/dokuwiki-template-fkstpl#32]
Jakmile bude přeložena hlavní stránka, nastavit odkaz loga na anglickou stránku.
https://github.com/fykosak/dokuwiki-template-fkstpl/blob/master/tpl_functions.php#L29

**Comment by cevro** [comment]
Merged in https://github.com/fykosak/dokuwiki-template-fkstpl/pull/33
