### ISSUE TITLE
Obrovský objem dat

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/dokuwiki-template-fkstpl#4]
Úvodní stránka natahuje 1.6 MB.

**Comment by LukasLedvina** [comment]
Druhý load je 130kB.

**Comment by cevro** [comment]
Potreba vykuchať css/cssAll.less, zmenšiť a cashovať vrchný obrázok. To by mohlo pomôcť.

**Comment by LukasLedvina** [comment]
Ten obrázek nemusí mít 0.5MB, ne? Tam stačím klidně nějaký zkomprimovaný.

**Comment by cevro** [comment]
Teoreticky aj orezaný, a možno aj prehnaný rutinou ml();

**Comment by uberales** [comment]
Ten horní obrázek by se měl ideálně střídat, tj. necachovat, ořezávat, komprimovat (z nějaké vybrané sady).
