### ISSUE TITLE
Sponzori

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/dokuwiki-template-fkstpl#7]
- K sazbě. Nad Bakalou se mi zdá, že je moc málo místa.
- Sponzoři bych možná nahradil "Partneři" a sponzor bych psal fakt u sponzorů, což MFF ani CSF nejsou.
- Loga bych udělal klikací.

**Comment by cevro** [comment]
> Sponzoři bych možná nahradil "Partneři" a sponzor bych psal fakt u sponzorů, což MFF ani CSF nejsou.
Obsah nieje forma

**Comment by cevro** [comment]
> K sazbě. Nad Bakalou se mi zdá, že je moc málo místa.

Opravené na teste, zatial nezagitované.

> Loga bych udělal klikací.

Opať sa budem opakovať -- Obsah nieje forma je to v dokuwiki syntaxi
