### ISSUE TITLE
Nove vysledkovky - sortovanie 

### ISSUE THREAD

**Issue by patoFKS** [fykosak/dokuwiki-template-fkstpl#8]
Pri sorteni podle skoly, jednotlivych uloh apod. by mal Student Pilny vzdy zostavat na prvom mieste (aby sa vedelo bodovanie uloh).

**Comment by cevro** [comment]
Po chviľe hľadania som objavil 
https://github.com/ascii-soup/Tablesorter-Static-Row-Plugin

Vyzerá, že to bude asi ono nasadím to u seba a podľa výsledku to pôjde na web.

**Comment by cevro** [comment]
Nasadený na webe staticRow a funguje to ako má.
http://fykos.cz/poradi/rocnik29/serie1
